### ISSUE TITLE
NOTICE: upcoming default branch name change

### ISSUE THREAD

**Issue by jesse-ross** [USGS-R/ds-gitflows-template#13]
The `master` branch of this repository will soon be renamed from `master` to `main`, as part of a coordinated change across the USGS-R and USGS-VIZLAB organizations.  This is part of a broader effort across the git community to use more inclusive language. For instance, [git](https://sfconservancy.org/news/2020/jun/23/gitbranchname/), [GitHub](https://github.com/github/renaming), and [GitLab](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/) have all changed or are in the process of changing their default branch name.

We will make this change early in the week of January 10, 2022. The purpose of this issue is to give notification of the change and provide information on how to make it go smoothly.

If you wish to make the change yourself rather than wait for us to do it, it can either be done manually or through some convenience functions in the `usethis` package.

- [ ] From your local version of the repository, change the remote branch name using [usethis](#-using-usethis) or [the manual method](#-manual-method).
- [ ] Verify that the local branches are changed as well (if using usethis) or change them yourselves (if using the manual method).
- [ ] If you have collaborators on this repository, give them a heads up by pointing them to this issue!
- [ ] Search within your repository for "master" so that you can change references (e.g. URLs pointing to specific commit points of files) to point to "main" instead.
- [ ] When you are done, feel free to close this issue!

### Using usethis
**Note: `usethis` must be version 2.1.2 or higher**

1. Run `usethis::git_default_branch_rename()`

The screen shot below shows the output of this command in addition to a few other commands. For more details see [here](https://usethis.r-lib.org/reference/git-default-branch.html).

![](https://user-images.githubusercontent.com/13890601/144508471-d2cf8b38-b686-4c7d-ba77-2f5ca2d8adec.png)

Note that if you have not yet set up git credentials for HTTPS, you can do so by [creating a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and using `gitcreds::gitcreds_set()` to register it with git.

![](https://user-images.githubusercontent.com/13890601/144508559-e45c2c72-07e9-41f1-b0f4-f675edd45045.png)

### Manual Method
1. Go to \<your repository\> -> Settings -> Branches and edit the default branch from `master` to `main`.
1. All members must update their local settings to match this change. They can either do this with `usethis::git_default_branch_rediscover()` (see above) or else run the following:
```r
git config --global init.defaultBranch main
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by lindsayplatt** [comment]
I am stuck on the token issue. When I run `gh_token_help()` it says that I am missing `user:email` permissions. I followed the instructions for re-creating a PAT by running `create_github_token()` and then `gitcreds::gitcreds_set()` but nothing seems to help. Is the problem that I should have my remotes set up with HTTPS instead of SSH?

**Comment by jesse-ross** [comment]
I don't think that the SSH remote is the problem. Mine is set up that way too. When I run `gh_token_help` I don't have any problems:

![image](https://user-images.githubusercontent.com/13890601/145281371-9d527707-93fb-4b04-8b90-e6ce97ff52ab.png)

so I think that the problem is just that your PAT is lacking that `user:email` permission. The one I made is ridiculously overpowered, with full permissions over everything. This points out a real weak spot: we need to document which permissions are required!

**Comment by lindsayplatt** [comment]
Do I have to restart R or anything? I just made a new token and checked all permissions accept for "delete repo", used the token when asked in `gitcreds::gitcreds_set()`, and it still gives me that error.

**Comment by jesse-ross** [comment]
So you did "replace token" when `gitcreds::gitcreds_set()` prompted you? I am a bit at sea, but one potential source of problems might be that there are a few ways that the git credentials can be cached (in a file store by git, in some kind of time-limited cache by git, or in a cache by R), and maybe you're running into some problem with the cached PAT being wrong.

You can run `gitcreds_set()` again and choose (3) to see your PAT in plain text and see whether it's the right one. Or restarting R might help. Or you could try to clear your slate with something like `keep_deleting = TRUE; while (keep_deleting) {gitcreds::gitcreds_delete(url = "https://github.com")}`.

It's probably obvious that I'm flummoxed here; sorry! Hopefully proper documentation of the required PAT permissions will keep this from happening to others.

**Comment by jesse-ross** [comment]
Oh, actually, just found this which gives helpful output including the head and tail of the PAT: `gh::gh_whoami()`. Could you please run that and see if it's the right PAT? And maybe paste the output?

**Comment by lindsayplatt** [comment]
Oh ... that is not the correct token. Interesting ... what I get back from `gitcreds::gitcreds_set()` and choosing (3) is not the same as what is returned from `gh::gh_whoami()`.

```
{
  "name": "Lindsay (Carr) Platt",
  "login": "lindsayplatt",
  "html_url": "https://github.com/lindsayplatt",
  "scopes": "repo, workflow",
  "token": "b6b1...9557"
} 
```

**Comment by jesse-ross** [comment]
It looks like `gh::gh_whoami()` is actually logging into github to see who github perceives you as, so I think that this is more trustworthy as a sign of what is going on than the `gitcreds::gitcreds_set()` output. I think we need to clear some cache or other. Would you mind trying this?

1. (optional) Restart R
1. Run this until it no longer has output: `gitcreds::gitcreds_delete(url = "https://github.com")`
1. Verify that your output from `gitcreds::gitcreds_get()` and `gh::whoami()` don't show any tokens (if you see any tokens in the output, run `gitcreds::gitcreds_delete(url = "https://github.com")` again)
![image](https://user-images.githubusercontent.com/13890601/145308662-b35a39ed-7db2-4760-a84d-811cf8742e60.png)
1. Run `gitcreds::gitcreds_set()` again and provide it the new powerful PAT
1. Verify that `gh::gh_whoami()` output is sane (scopes look good, PAT matches what you expect)
1. `usethis::git_default_branch_rename()`

**Comment by lindsayplatt** [comment]
It might be worth hopping on the phone at some point ... I used `gitcreds::gitcreds_delete(url = "https://github.com")` and also tried without specifying the URL. That deleted the token returned by `gitcreds::gitcreds_get()` but I still get a token from `gh::gh_whoami()`.

**Comment by lindsayplatt** [comment]
Output from `gitcreds::gitcreds_get()`

```
<gitcreds>
  protocol: NA
  host    : NA
  username: NA
  password: <-- hidden -->
```

Output from `gitcreds::gitcreds_get()`:

```
usethis::gh_token_help()
* GitHub host: 'https://github.com'
* Personal access token for 'https://github.com': '<discovered>'
* GitHub user: 'lindsayplatt'
* Token scopes: 'repo, workflow'
x Token lacks recommended scopes:
  - 'user:email': needed to read user's email addresses
  Consider re-creating your PAT with the missing scopes.
  `create_github_token()` defaults to the recommended scopes.
x Can't retrieve registered email addresses from GitHub.
  Consider re-creating your PAT with the 'user' or at least 'user:email' scope.
```

**Comment by jesse-ross** [comment]
For history's sake: the problem here was that this repo is a template repository. The `usethis` workflow doesn't work on those.
